### ISSUE TITLE
Github Copilot suggestions are unclear.

### ISSUE THREAD

**Issue by konstantinzolotarev** [MordFustang21/zed-one-dark-pro#1]
Hello first of all big than you for your work. really like the theme. 

The only thing I noticed so far is that color of variable is almost same as github copilot suggestion. 
As a result it's very hard to understand where is your code and where is suggestion. 

Example with default `One Dark` theme:

![Screenshot 2024-02-25 at 13 54 46](https://github.com/MordFustang21/zed-one-dark-pro/assets/286431/8104ce8d-1e66-4624-a959-b0c39b50aa73)

And here is with `One Dark Pro`:
Where `.set_active_span...` is suggestion and difference to `tracer.` (that is hand written code) is barely visible.

![Screenshot 2024-02-25 at 13 55 02](https://github.com/MordFustang21/zed-one-dark-pro/assets/286431/8ed1de76-337e-4fe7-a11a-b7cc3edb92c9)

May be color of suggestions could be somehow changed to something else ?

**Comment by MordFustang21** [comment]
Yeah it definitely needs to be better. I'll see if I can figure out what value adjusts that.
