### ISSUE TITLE
Text selection color is hard to visualize

### ISSUE THREAD

**Issue by joseluisq** [MordFustang21/zed-one-dark-pro#19]
I noted that when selecting a text, the background color is too dark. Making it easy to lose focus when selecting multiple text occurrences across a file.

For example, note the _dark blue_ selection in zed-one-dark-pro:
<img width="351" alt="image" src="https://github.com/user-attachments/assets/d2b9ece1-f402-48a1-9eaa-a8c506c3adad">

versus the same selection in a brighter color in VSCode / One Dark Pro which looks much better:
<img width="418" alt="image" src="https://github.com/user-attachments/assets/9c97d54c-87b0-442e-9a6e-a22599822875">

Using a bright color should help a lot since the editor's background is already darker.

**Comment by suhaybu** [comment]
To add to this issue, when selecting text in documentation, it becomes completely un readable. I will make a PR fix for both of these problems.

![CleanShot 2024-08-17 at 02 47 52](https://github.com/user-attachments/assets/abbe23bb-08dd-4f03-877e-c5204a2884c8)


edit: Made PR to solve both of our problems https://github.com/MordFustang21/zed-one-dark-pro/pull/20#issue-2471228567
