### ISSUE TITLE
Warning text is hard to read

### ISSUE THREAD

**Issue by MordFustang21** [MordFustang21/zed-one-dark-pro#6]
Should be an easy issue for anyone looking to make a PR with changes to 
`warning, warning.background, and warning.border`

![image](https://github.com/MordFustang21/zed-one-dark-pro/assets/8725798/c1dc1871-1dbd-4874-8d1c-43fab9c804b0)

**Comment by Ph0enixKM** [comment]
Not only warning. Error text is also hard to read. I think that black text on the bright red would be much more readable.

<img width="706" alt="Zrzut ekranu 2024-03-11 o 17 00 28" src="https://github.com/MordFustang21/zed-one-dark-pro/assets/29208124/fb15512d-4822-4999-8ce1-01881232dabd">

**Comment by Ph0enixKM** [comment]
The same issue applies to info bars

<img width="677" alt="Zrzut ekranu 2024-03-11 o 17 02 45" src="https://github.com/MordFustang21/zed-one-dark-pro/assets/29208124/2a4b1d3c-2549-4349-bbef-61e361023bcb">

**Comment by suhaybu** [comment]
> Should be an easy issue for anyone looking to make a PR with changes to `warning, warning.background, and warning.border`

Overriding `warning.background` was not sufficient. I also had to modify `hint.background` and `error.background`.

Will make a PR for this.

Edit:
Made a PR here: https://github.com/MordFustang21/zed-one-dark-pro/pull/17#issue-2447300516

**Comment by suhaybu** [comment]
@MordFustang21 I think we can safely close this issue since the fix was rolled in v0.0.4
